# Generated by Django 4.2.6 on 2023-12-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('car_price', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('quan', models.IntegerField(default=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/media/uploads/')),
                ('buyer', models.CharField(max_length=200)),
                ('brand', models.ManyToManyField(to='brands.brandmodel')),
            ],
        ),
        migrations.CreateModel(
            name='commentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('userPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.userpostmodel')),
            ],
        ),
    ]
